### ISSUE TITLE
Getting Error 500, cannot find examples in documentation.

### ISSUE THREAD

**Issue by CryogenicQuack** [playht/text-to-speech-api#2]
Hello!

When sending a POST request from a python script using the Requests module, the response is a code 500.

Request is:
requests.post('https://play.ht/api/v1/./convert',headers={'Authorization':user_key,'X-User-ID':user_id},data=dict_args)

Where data consists of 

dict_args = {"voice":chosen_voice,"content":body,"title":name}
being all of the keys variables of type string ("content" was also tested with a list of strings containing 1 string)

user_key, user_id as type string.

The lack of examples in the documentation is leaving me out of ideas.

**Comment by HazemAM** [comment]
@CryogenicQuack Thanks for opening an issue!

The dot at the start of endpoint URLs are meant to indicate the relativity of the path with the base URL of the API, and is not meant to be included in the request URL.

So instead of sending the request to `https://play.ht/api/v1/./convert`, you should send it to **`https://play.ht/api/v1/convert`**. That’s it!

I’ll close this issue, but please feel free to open a new one if you’re still facing any issues.
